# Generated by Django 4.0 on 2022-01-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulklot', '0002_alter_lotrequest_req_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotrequest',
            name='location',
            field=models.CharField(choices=[('舎人公園', '舎人公園')], max_length=100),
        ),
    ]
