# Generated by Django 4.0 on 2022-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulklot', '0003_alter_lotrequest_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotrequest',
            name='location',
            field=models.CharField(choices=[('舎人公園', '舎人公園')], default='舎人公園', max_length=100),
        ),
    ]
