# Generated by Django 4.0 on 2022-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulklot', '0004_alter_lotrequest_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotrequest',
            name='sport',
            field=models.CharField(choices=[('テニス（人工芝）', 'テニス（人工芝）')], default='テニス（人工芝）', max_length=100),
        ),
    ]
