# Generated by Django 4.0 on 2022-01-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bulklot', '0006_alter_lotrequest_location_alter_lotrequest_sport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotrequest',
            name='location',
            field=models.CharField(choices=[('10,2', '舎人公園')], default='舎人公園', max_length=100, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='lotrequest',
            name='req_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='申込日'),
        ),
        migrations.AlterField(
            model_name='lotrequest',
            name='sport',
            field=models.CharField(choices=[('130', 'テニス（人工芝）')], default='テニス（人工芝）', max_length=100, verbose_name='種目'),
        ),
        migrations.AlterField(
            model_name='lotrequesttime',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='lotrequesttime',
            name='lot_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulklot.lotrequest', verbose_name='抽選申込'),
        ),
        migrations.AlterField(
            model_name='lotrequesttime',
            name='time',
            field=models.CharField(choices=[('900_1100', '09:00～'), ('1100_1300', '11:00～'), ('1300_1500', '13:00～'), ('1500_1700', '15:00～'), ('1700_1900', '17:00～')], max_length=40, verbose_name='時間帯'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('tmgbc_id', models.CharField(max_length=8, verbose_name='TMGBC登録番号')),
                ('tmgbc_password', models.CharField(max_length=15, verbose_name='TMGBCパスワード')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='所有者')),
            ],
        ),
    ]
