# Generated by Django 4.0 on 2022-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulklot', '0009_lotrequest_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotrequesttime',
            name='status',
            field=models.CharField(choices=[('10', '待機中'), ('20', '処理中'), ('30', '完了'), ('40', 'エラー')], default='10', max_length=40, verbose_name='ステータス'),
        ),
    ]
